name: Build Arduino

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@81d310742121c928ea9c8bbd407b4217b432ae02  # v2.0.0

      - name: Initialize Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Set configs
        run: |
          cp ./src/Arduino/config_default.h ./src/Arduino/config.h
          cp ./src/Arduino/secret_default.h ./src/Arduino/secret.h
          cp ./src/ESP32/config_default.h ./src/ESP32/config.h
          cp ./src/ESP32/secret_default.h ./src/ESP32/secret.h

      - name: Compile
        run: |
          arduino-cli compile ./src/Arduino
          arduino-cli compile ./src/ESP32
