name: Build Arduino

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@81d310742121c928ea9c8bbd407b4217b432ae02  # v2.0.0

      - name: Initialize Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Install required board core
        run: arduino-cli core install arduino:avr@1.8.7  # např. pro Arduino Uno
          
      - name: Install custom library
        run: |
          arduino-cli lib install "MQTTESP8266@5.1.2"

      - name: Set configs
        run: |
          cp config_default.h config.h

      - name: Compile Arduino project
        run: |
          arduino-cli compile --fqbn arduino:avr:uno ./
