name: Build Arduino

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@81d310742121c928ea9c8bbd407b4217b432ae02  # v2.0.0

      - name: Initialize Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Set configs
        run: |
          cp config_default.h config.h
          cp secret_default.h secret.h

      - name: Compile Arduino project
        run: |
          arduino-cli compile --profile LSSensor_Uno ./
